FROM node:18-alpine

WORKDIR /app

# copiar dependências primeiro
COPY tattoo-frontend/package*.json ./
RUN npm install

# copiar o resto do código
COPY tattoo-frontend/ .

EXPOSE 4200

CMD ["npm", "start"]
