# Generated by Django 5.2.6 on 2025-09-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/clientes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tatuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tatuador', models.CharField(max_length=150)),
                ('nome_estudio', models.CharField(blank=True, max_length=150, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True)),
                ('experiencia', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/tatuadores/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estilos', models.ManyToManyField(blank=True, to='tatuagem.estilo')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('pendente', 'Pendente'), ('reservado', 'Reservado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='tatuagem.cliente')),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='tatuagem.tatuador')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tatuador', 'data', 'hora_inicio'), name='unique_horario_tatuador')],
            },
        ),
    ]
