# Generated by Django 5.2.7 on 2025-10-15 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tatuador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TatuagemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem principal da tatuagem.', upload_to='tattoos/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tatuagem.estilo')),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Tatuador',
        ),
    ]
