# Generated by Django 5.2.7 on 2025-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0002_alter_agenda_tatuador_tatuagempost_delete_tatuador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='TEMP_PASSWORD_REQUIRED', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='posts_curtidos',
            field=models.ManyToManyField(blank=True, related_name='curtido_por', to='tatuagem.tatuagempost'),
        ),
    ]
