# Generated by Django 5.2.7 on 2025-11-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0003_cliente_password_cliente_posts_curtidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
