# Generated by Django 5.2.7 on 2025-11-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0003_cliente_password_cliente_posts_curtidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('pendente', 'Pendente'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='disponivel', max_length=20),
        ),
    ]
