# Generated by Django 5.2.7 on 2025-11-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0004_agenda_nome_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='tatuagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tatuagem', to='tatuagem.tatuagempost'),
        ),
    ]
