# Generated by Django 5.2.7 on 2025-11-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0005_agenda_tatuagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuagempost',
            name='duracao_estimada',
            field=models.PositiveIntegerField(default=60, help_text='Duração estimada em minutos'),
        ),
    ]
