# Generated by Django 5.2.7 on 2025-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0006_tatuagempost_duracao_estimada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatuagempost',
            name='duracao_estimada',
        ),
        migrations.AddField(
            model_name='tatuagempost',
            name='tempo_estimado',
            field=models.PositiveIntegerField(default=60, help_text='Tempo estimado em minutos'),
        ),
    ]
