# Generated by Django 5.2.7 on 2025-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuagem', '0007_remove_tatuagempost_duracao_estimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatuagempost',
            name='estilo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
